websiteYoutube/music/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^login/$', views.UserFormLogin.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^boxcars/$', views.BoxcarsView.as_view(), name='Boxcars'),

    # game page
    #url(r'^games/$', views.GamesView.as_view(), name='games'),
    url(r'^games/$', views.GameList.as_view(), name='games'),

    # /music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # music/album/add
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # music/album/2
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # music/album/2/delete
    url(r'^album/(?P<pk>[0-9]+)/delete$', views.AlbumDelete.as_view(), name='album-delete'),

    # /music/album_id/favorite
   # url(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),

]

#urlpatterns = format_suffix_patterns(urlpatterns)

websiteYoutube/websiteYoutube/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from music import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^games/', views.GameList.as_view()),
    url(r'^music/', include('music.urls')),
    url(r'^userdata/', views.ExampleView.as_view()),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns = format_suffix_patterns(urlpatterns)
if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

websiteYoutube/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album (models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' '+ 'by'+ ' ' + self.artist

class Song(models.Model):#associated with a album
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

class Game (models.Model):
    game_title = models.CharField(max_length=100)
    game_logo = models.FileField()

    def __str__(self):
        return self.game_title

websiteYoutube/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm ( forms.ModelForm ):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:  # information about the class
        model = User
        fields = ['username','email' ,'password']
        #fields = ['username', 'email', 'first_name', 'last_name', 'password']



websiteYoutube/music/views.py
from django.views import generic
from django.views.generic import FormView, RedirectView
from .models import Album, Song, Game
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm
from rest_framework.views import APIView
from .serializers import GameSerializer
from rest_framework.response import Response
from .models import Game
from django.shortcuts import get_object_or_404
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView


class ExampleView(APIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        content = {
            'user': str(request.user),  # `django.contrib.auth.User` instance.
            'auth': str(request.auth),  # None
            'name': str(request.user.first_name),
            'email': str(request.user.email),
            'pass': str(request.user.password),

        }
        return Response(content)

class GameList(APIView):
    def get (self, request):
        games = Game.objects.all()
        serializer = GameSerializer(games, many=True)
        return Response (serializer.data)
        #return serializer.data

    def post (self):
        pass

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

class BoxcarsView(generic.ListView):
    template_name = 'music/Boxcars.html'
    def get_queryset(self):
         return Game.objects.all()

class DetailView (generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate (CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate (UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete (DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # dispaly new form for register
    def get(self, request):
        form = self.form_class(None)
        return  render(request, self.template_name, {'form':form})

    # process form data
    def post (self, request):
        print("1")
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit = False) # just store it normally
            # clean and normalize data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #email = form.cleaned_data['email']
            #first_name = form.cleaned_data['first_name']
            #last_name = form.cleaned_data['last_name']
            user.set_password(password)
            user.save()
            print("2")

            # return user objects if credentials are correct
            user = authenticate(username = username, password = password)
            if user is not None :
                print("3")
                #if user.is_active :
                login(request, user)
                return redirect('music:index')
        return render(request, self.template_name, {'form': form})

class UserFormLogin(View):
    form_class = UserForm
    template_name = 'music/login_form.html'

    # dispaly new form for login
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        print("1")
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        user = authenticate(request, username=username, password=password, email=email)
        form = self.form_class(request.POST)
        if user is not None:
            print("3")
            # if user.is_active :
            login(request, user)
            return redirect('music:index')
        return render(request, self.template_name, {'form': form})

class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/music/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

def logout_view(request):
    logout(request)


class GamesView(generic.ListView):
    template_name = 'music/games.html'
    def get_queryset(self):
        return Game.objects.all()


'''
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index (request):
    all_albums = Album.objects.all()
    return  render(request,'music/index.html', {'all_albums': all_albums})

def detail (request, album_id):
    album = get_object_or_404(Album, pk= album_id)
    songs = Song.objects.filter(album=album_id)
    return render(request,'music/detail.html', {'album': album, 'songs':songs})

def favorite (request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get (pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_massage': "You did not select the valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return  render(request, 'music/detail.html', {'album': album})
'''

websiteYoutube/templates/music/Boxcars.html
{% extends 'music/base.html' %}
{% block body %}

    <p>
    Hold on to me
Don't let me go
Who cares what they see?
Who cares what they know?
Your first name is Free
Last name is Dom
Cause you still believe in where we're from
Man's red flower
It's in every living thing
Mind use your power
Spirit use your wings
    </p>
{% endblock %}


websiteYoutube/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title  %}Add new Album{% endblock %}
{% block album_active  %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}





websiteYoutube/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Idea{% endblock %}</title>
    <!-- load the path to your static files -->
{% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js" ></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- header --->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:Boxcars' %}">Boxcars</a>
        </div>
        <!--- Items --->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; <!--- that was album before --->
                        {% if request.user.is_authenticated %}Welcome '{{ request.user.username }}'
                        {% else %}<a href="{% url 'music:login' %}">Login</a>{% endif %}
                    </a>
                </li>
                <li>
                </li>
                <li class="">
                    <a href="{% url 'music:games' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Matches<!--- songs  --->
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

websiteYoutube/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album.album_title }} songs{% endblock %}
{% block body %}
    <img src="{{ album.album_logo.url }}">
    <h1>Here is {{ album.album_title }} songs by {{ album.artist }}</h1>
    {% if songs %}
        <ul>

        {% for song in songs  %}
            <li><p>{{ song.song_title }}.{{ song.file_type }}</p></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>This album has no song</p>
    {% endif %}
    {% if error_massage %}
        <p><strong>{{ error_massage }}</strong></p>
    {% endif %}

    <form action="{% url 'music:detail' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}"  name="song" value="{{ song.id }}" />
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}
                {% if song.is_favorite %}
                    <img src="https://www.cloudynights.com//public/style_images/master/star.png">
                {% endif %}
            </label><br>

        {% endfor %}
        <input type="submit" value="Favorite">
    </form>
{% endblock %}


websiteYoutube/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-10" >
            <span class="text small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

websiteYoutube/templates/music/games.html
{% extends 'music/base.html' %}
{% block title  %}Choose a game{% endblock %}
{% block album_active  %}active{% endblock %}

{% block body %}
    {% if object_list %}
        <h1>Here is my all Games</h1>
        <ul>
            {% for game in object_list %}
            <li>
                <a href="" >{{ game.game_title }}</a>

            </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You dont have any games</h3>
    {% endif %}
{% endblock %}


websiteYoutube/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
    {% if object_list %}
        <h1>Here is my all Albums</h1>
        <ul>
            {% for album in object_list %}
            <li>
                <a href="{% url 'music:detail' album.id %}" >{{ album.album_title }}
                <form method="post" style="display: inline;" action="{% url 'music:album-delete' album.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                </a>

            </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You dont have any albums</h3>
    {% endif %}
{% endblock %}

websiteYoutube/templates/music/login_form.html
{% extends 'music/base.html' %}
{% block title  %}Login{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Create a New acount</h1>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}





websiteYoutube/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title  %}Register{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>Create a New acount</h1>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}





websiteYoutube/templates/music/song_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>